package sim;


/**
* sim/SimCorbaServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sim.idl
* Segunda-feira, 9 de Dezembro de 2013 18h11min56s BRT
*/

public interface SimCorbaServerOperations 
{
  String login (String nickname, sim.SimCorbaClient client) throws sim.UserExists;
  void logout (String id) throws sim.AnonymID;
  void write (String from, String text) throws sim.AnonymID;
  void writeTo (String from, String to, String message) throws sim.AnonymID;
  void startRadar (String nickname, String location);
  void stopRadar (String nickname);
  String changeLocation (String nickname, String location);
  String listNearlyClients (String nickname);
  String addRoom (String roomName);
  String getRoom (String clientName);
  String listRooms ();
  String changeClientRoom (String clientName, String roomName);
} // interface SimCorbaServerOperations
