package sim;


/**
* sim/SimCorbaClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sim.idl
* Segunda-feira, 9 de Dezembro de 2013 18h11min56s BRT
*/

public interface SimCorbaClientOperations 
{
  void update (String message);
} // interface SimCorbaClientOperations
