package sim;

/**
* sim/UserExistsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sim.idl
* Segunda-feira, 9 de Dezembro de 2013 18h11min56s BRT
*/

public final class UserExistsHolder implements org.omg.CORBA.portable.Streamable
{
  public sim.UserExists value = null;

  public UserExistsHolder ()
  {
  }

  public UserExistsHolder (sim.UserExists initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sim.UserExistsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sim.UserExistsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sim.UserExistsHelper.type ();
  }

}
